# postgres config

development:
  adapter: postgresql
  database: myapp_development

test:
  adapter: postgresql
  database: myapp_test

production:
  adapter: postgresql
  database: myapp_test
  host: localhost